//
// Copyright (C) 2012 Claudiu Tasca <clawgm [at] gmail.com>, Marius Petcu <marius
// [at] porkholt.org>, Nandor Licker <licker.nandor [at] gmail.com>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

#ifndef _HTTP_HEADER_CODES_
#define _HTTP_HEADER_CODES_

typedef enum
{ 
	// 1xx: Information
	HTTP_CONTINUE = 100,
	HTTP_SWITCHING_PROTOCOLS,
	HTTP_CHECKPOINT = 103,

	// 2xx: Successful
	HTTP_OK = 200,
	HTTP_CREATED,
	HTTP_ACCEPTED,
	HTTP_NON_AUTHORITATIVE_INFORMATION,
	HTTP_NO_CONTENT,
	HTTP_RESET_CONTENT,
	HTTP_PARTIAL_CONTENT,

	// 3xx: Redirection
	HTTP_MULTIPLE_CHOICES = 300,
	HTTP_MOVED_PERMANENTLY,
	HTTP_FOUND,
	HTTP_SEE_OTHER,
	HTTP_NOT_MODIFIED,
	HTTP_SWITCHED_PROXY,
	HTTP_TEMPORARY_REDIRECT = 307,
	HTTP_RESUME_INCOMPLETE,

	// 4xx: Client Error
	HTTP_BAD_REQUEST = 400,
	HTTP_UNAUTHORIZED,
	HTTP_PAYMENT_REQUIRED,
	HTTP_FORBIDDEN,
	HTTP_NOT_FOUND,
	HTTP_METHOD_NOT_ALLOWED,
	HTTP_NOT_ACCEPTABLE,
	HTTP_PROXY_AUTHENTIFICATION_REQUIRED,
	HTTP_REQUEST_TIMEDOUT,
	HTTP_CONFLICT,
	HTTP_GONE,
	HTTP_LENGTH_REQUIRED,
	HTTP_PRECONDITION_FAILED,
	HTTP_REQUEST_ENTITY_TOO_LARGE,
	HTTP_REQUEST_URI_TOO_LONG,
	HTTP_UNSUPPORTED_MEDIA_TYPE,
	HTTP_REQUESTED_RANGE_NOT_SATISFIABLE,
	HTTP_EXPECTATION_FAILED,

	// 5xx: Server Error
	HTTP_INTERNAL_SERVER_ERROR = 500,
	HTTP_NOT_IMPLEMENTED,
	HTTP_BAD_GATEWAY,
	HTTP_SERVICE_UNAVAILABLE,
	HTTP_GATEWAY_TIMEOUT,
	HTTP_VERSION_NOT_SUPPORTED,
	HTTP_NETWORK_AUTHENTICATION_REQUIRED = 511
} HTTP_CODES ;

#endif